sudo: required

services:
  - docker

before_install:
- docker pull craberger/emptyheaded

script: "source ./tests/testAll.sh"

notifications:
  email:
    - craberger@gmail.com

branches:
  only:
    - master
