sudo: required

services:
  - docker

before_install:
- docker pull craberger/emptyheaded

script:
- docker run craberger/emptyheaded /bin/bash -c "cd /root/EmptyHeaded; source ./tests/testAll.sh"

notifications:
  email:
    - craberger@gmail.com

branches:
  only:
    - master
