sudo: false

language: scala

scala:
  - 2.11.2

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-format-3.4
    - g++-4.9
    - libtbb-dev
    - libgtest-dev
    - libjemalloc-dev

install:
  - conda install -y pandas

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH 

before_script:
  - curl -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar

script: "source ./tests/testAll.sh"

notifications:
  email:
    - craberger@gmail.com

branches:
  only:
    - master
